language: python
python:
- '3.7'
dist: xenial
install:
- docker build -t aircontrol/underlord-server .
script: python -m pytest
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: travis
  skip_cleanup: true
